name: CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [21]
    name: Java ${{ matrix.java }} sample

    steps:
    - name: Checkout calimero-core
      uses: actions/checkout@v4
      with:
        repository: calimero-project/calimero-core
        path: calimero-core
    - name: Checkout calimero-tools
      uses: actions/checkout@v4
      with:
        repository: calimero-project/calimero-tools
        path: calimero-tools
    - name: Checkout calimero-rxtx
      uses: actions/checkout@v4
      with:
        repository: calimero-project/calimero-rxtx
        path: calimero-rxtx
    - name: Checkout calimero-gui
      uses: actions/checkout@v4
      with:
        path: calimero-gui
    - name: setup
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      run: |
        cd calimero-gui
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd calimero-gui
        ./gradlew build
