release:
  needs: package
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v6

    - name: Download all artifacts
      uses: actions/download-artifact@v8
      with:
        path: dist

    - name: Get project version
      id: version
      shell: bash
      run: |
        VERSION=$(./gradlew -q properties | grep "^version:" | awk '{print $2}')
        echo "value=$VERSION" >> $GITHUB_OUTPUT

    - name: Generate timestamp
      id: timestamp
      shell: bash
      run: |
        echo "value=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Release packages
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        tag_name: ${{ steps.version.outputs.value }}.${{ steps.timestamp.outputs.value }}
        name: ${{ steps.version.outputs.value }} Build ${{ steps.timestamp.outputs.value }}
        prerelease: true
        files: dist/**
