name: Build Packages

on:
  push:
    branches:
      - feat/pkg
    tags:
      - '*'

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build package
        run: ./gradlew package
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: app-${{ matrix.os }}
          path: |
            build/package/app/*.tar.gz
            build/package/app/*.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: package
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist

      - name: Get project version
        id: version
        shell: bash
        run: |
          VERSION=$(./gradlew -q properties | grep "^version:" | awk '{print $2}')
          echo "value=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate timestamp
        id: timestamp
        shell: bash
        run: |
          echo "value=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Release packages
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.version.outputs.value }}.${{ steps.timestamp.outputs.value }}
          name: ${{ steps.version.outputs.value }} Build ${{ steps.timestamp.outputs.value }}
          prerelease: true
          files: dist/**
